### ISSUE TITLE
Add helm chart

### ISSUE THREAD

**Issue by koeberlue** [Wingysam/Christmas-Community#10]
It would be great to install this app on a kubernetes cluster. For me the easiest way would be an official helm chart: https://helm.sh

Would it be possible to add one?

**Comment by Wingysam** [comment]
I've never used k8s yet, I personally use Nomad, but I can look into writing a helm chart. Thanks!

**Comment by ndlanier** [comment]
I just found this repo from an awesome list. Didn't see anything in artifacthub for it. Guess I can get a helm chart going.

**Comment by Wingysam** [comment]
That would be awesome, thank you!

**Comment by ndlanier** [comment]
@Wingysam do you want me to add it to this repo or would you rather I host my own repo for the chart?

**Comment by ndlanier** [comment]
PR ready for review

**Comment by ndlanier** [comment]
Ready for review again haha

**Comment by ndlanier** [comment]
@koeberlue the chart is available in the repo. You will have to download the chart folder or clone the repo and point to the chart directory for now until a hosting solution for the chart is decided upon.

@Wingysam please assign the issue to me and close since PR #43 has implemented this request.
