### ISSUE TITLE
Crossed off items giving pledges away.

### ISSUE THREAD

**Issue by imcompiling** [Wingysam/Christmas-Community#113]
I updated to 1.34.1 today from 1.32.0 and one of my users discovered that they could see the crossed off text in their personal wish-list. I tested it by impersonating their account and I could see it, but I did not see the same thing on my own account or another user's account. I don't know what made this account special. The user that could see was not an admin, my account is, and the 3rd account that I checked was not an admin.

I am unsure how to reproduce the error, but I can probably set up a clone of my data for testing if that helps.

**Comment by cj13579** [comment]
I've been able to replicate this. I'll submit a PR.
