### ISSUE TITLE
Request: Display english version if string isn't translated into the selected language yet

### ISSUE THREAD

**Issue by jskiddie** [Wingysam/Christmas-Community#118]
currently says something along the lines of `VAR hasn't been translated to English yet.` but since there is access to the information which sting was requested anyways ```_NOT_LOCALIZED: key => `${key} hasn't been translated to English yet.`,``` can't `key` be resolved to the english language file 😬 ?
Maybe append something along the lines of `(not yet translated)`

**Comment by Wingysam** [comment]
Yeah, one minute! I'll do it and push a new release.

**Comment by Wingysam** [comment]
v1.35.0 has this done and will be released shortly.

**Comment by jskiddie** [comment]
thx :)
