### ISSUE TITLE
Request: Add item on top

### ISSUE THREAD

**Issue by L041S** [Wingysam/Christmas-Community#130]
Hello,
Currently if you want to add an item you have to go to the bottom wich can be time consuming on mobile if you have a lot of items and need to add multiple links.

It could be interesting to add a setting to put the field on top of the page.

**Comment by cj13579** [comment]
I think that would take up too much space. However, what about something like this?

![image](https://github.com/user-attachments/assets/65b8e2f7-10d9-4b2c-95bf-81b8e356ea8d)

This button links down the form. That way, you can at least get down to that area of the page more quickly?

**Comment by Wingysam** [comment]
Yeah that seems like the best way to do this!
