### ISSUE TITLE
Default Admin Credentials

### ISSUE THREAD

**Issue by peskyAdmin** [Wingysam/Christmas-Community#136]
I cant not find default admin credentials or place to set them. tried going to "/" on http but that just forwards to /login.

<img width="674" alt="image" src="https://github.com/user-attachments/assets/963abc41-3aa5-488f-9773-496a60c8aaf7">

having default admin credentials in docker or env file would be nice

**Comment by peskyAdmin** [comment]
okay i got in using what is displayed in the prompt. that should atleats be added to the readme.

**Comment by Wingysam** [comment]
Going to / should redirect to the setup page. This sounds like a bug.

**Comment by kfoxton** [comment]
Just found this application via Community Application in Unraid. Having the same issue, any attempt to go to / redirects back to the /login page, with no ability to login.

Is there a default admin login that can be used to start?

**Comment by Wingysam** [comment]
There is not a default admin password. It's meant to redirect you to /setup if there are no accounts.

**Comment by Nevarro** [comment]
I've got the same problem. I can't set any credentials. / or /setup doesn't work.

**Comment by JohnGrosshans** [comment]
For those using the unraid template one of the fields is "Login Failure Redirect" it defaults to `/login` .
Change this to `/setup`
Once the container starts up you can go to the page and enter your new admin user and password. This will update the db with the new admin user and then the page will crash.
Edit the settings on the app again and change it back to `/login` .

This will get you in.

Side note the dbs directory where the sql lite databases are store have a field where it says the dbs are in path /dbs but this is inside the container. If you want this to live on outside of the container I'd recommend putting it in /data/dbs since the /data path is setup to be in your appsdata directory. That way the DB lives on between containers.

**Comment by Wingysam** [comment]
Oh okay, who maintains the Unraid template? Is that something automatically done that I can fix or is there someone I can contact?

**Comment by bckthomas** [comment]
Click on show more settings to see the "login failure redirect" variable.
But it doesn't work for me

**Comment by kfoxton** [comment]
> For those using the unraid template one of the fields is "Login Failure Redirect" it defaults to `/login` . Change this to `/setup` Once the container starts up you can go to the page and enter your new admin user and password. This will update the db with the new admin user and then the page will crash. Edit the settings on the app again and change it back to `/login` .
> 
> This will get you in.
> 
> Side note the dbs directory where the sql lite databases are store have a field where it says the dbs are in path /dbs but this is inside the container. If you want this to live on outside of the container I'd recommend putting it in /data/dbs since the /data path is setup to be in your appsdata directory. That way the DB lives on between containers.

I followed these settings after doing a fresh install on UnRaid and they worked!  I will put in a issue with the user that contributed the template.

**Comment by nwithan8** [comment]
> Oh okay, who maintains the Unraid template? Is that something automatically done that I can fix or is there someone I can contact?

Hey there, I'm the guy who made the Unraid template, apologies for the error. I just patched the template with these fixes, should populate in a few hours for new users.

**Comment by cj13579** [comment]
Its awesome that there is a template! 

I'm not an Unraid user myself but I wonder if we could link to this in the README for those that are?

**Comment by nwithan8** [comment]
Good idea. Can just say that it can be found by searching "Christmas Community" in the Community Apps store and installing it from grtgbln's repository (the only one that will pop up on the search results page), then follow the instructions to configure.

Unraid users will know what that all means.

**Comment by Wingysam** [comment]
The unraid app has been added to the README.
