### ISSUE TITLE
Can’t open this page because too many redirects occurred

### ISSUE THREAD

**Issue by servebeer** [Wingysam/Christmas-Community#142]
I just installed Christmas-Community on my Unraid server. It installed and stared with no errors. The first time I ran it, it had me create an administrative account, and now, I cannot get to a login page as every browser I try gives me a “ Can’t open this page because too many redirects occurred“ error.

**Comment by servebeer** [comment]
Looks like I jumped the gun. Whomever made the Unraid Appstore Template for it, forgot to add “/login” to the end of the URL variable.

**Comment by Wingysam** [comment]
I've never used Unraid before. Is the template on GitHub somewhere so I can make a PR to fix it?

**Comment by servebeer** [comment]
> I've never used Unraid before. Is the template on GitHub somewhere so I can make a PR to fix it?

According to the Unraid App Store, the maintainer's GitHup repo for this is: https://github.com/nwithan8/unraid_templates
