### ISSUE TITLE
Add doc "how to adding supported site"

### ISSUE THREAD

**Issue by zethis** [Wingysam/Christmas-Community#15]
Can you provide a doc to add a supported site ?
Too much site are only available in one language, so like this we can do a PR to add a new supported site :)

Thanks !

**Comment by Wingysam** [comment]
It's in a library on my GitLab. I'll migrate that to GitHub and provide instructions on adding additional sites. Thanks!

**Comment by Wingysam** [comment]
This is done, thanks for proposing this!
