### ISSUE TITLE
Prices not captured from Amazon links

### ISSUE THREAD

**Issue by mog1919** [Wingysam/Christmas-Community#20]
When adding an item with an Amazon link, the "Price" field for the item on the wish list is not populated.

For example, if I use the link
https://www.amazon.com/dp/B01N3A4070

I see a price of $19.82 on the Amazon detail page, but nothing on my wishlist entry.  I've had this same issue for several Amazon items that I've added.  The "Image" and "Name" fields work fine; only "Price" is not working.

I am using version 1.29.0 from the Docker image at https://hub.docker.com/r/wingysam/christmas-community/tags.

**Comment by Wingysam** [comment]
Thanks, I'll look into it.

**Comment by Wingysam** [comment]
This has been fixed in get-product-name [#b60f9924](https://gitlab.com/wingysam/get-product-name/-/commit/b60f99243bcfa8107fc845a538d59313150ef6cb).
