### ISSUE TITLE
Collapsible wishlists page

### ISSUE THREAD

**Issue by Beeez** [Wingysam/Christmas-Community#22]
Interested in a feature/UI change that allows you to view each users list from the main screen by collapsing each users section. 

![image](https://user-images.githubusercontent.com/46723579/192280958-7bf6e9c1-5baf-45bf-9782-f30805d0f160.png)

**Comment by Wingysam** [comment]
This seems doable for clients with JavaScript enabled (essentially everyone), but I'm not able to put the time in at the moment. I might be able to do this in mid-October.
