### ISSUE TITLE
"You did not pledge for this"

### ISSUE THREAD

**Issue by Wingysam** [Wingysam/Christmas-Community#31]
If someone adds an item to someone else's wishlist without pledging for it then tries to delete the item, this error is thrown.
![image](https://user-images.githubusercontent.com/18403742/193717595-e5fa9ec9-c9c0-4349-979f-f8c492594f7c.png)

**Comment by coalio** [comment]
Can you include steps to replicate this bug from a clean setup? 

i.e. "create a secondary user via x method -> log out and log into main user"

Can't seem to find an option to create another user apart of the admin account in the website.

**Comment by Wingysam** [comment]
I should be able to record a clip of triggering the bug from a clean install tomorrow. 

You can create accounts from the admin panel in the drop-down of the navbar.

**Comment by Wingysam** [comment]
Here are the reproduction steps:
https://streamable.com/0fat2u

**Comment by coalio** [comment]
Thanks, I'll take a look on it

**Comment by Wingysam** [comment]
Fixed by #40
