### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by hilsonp** [Wingysam/Christmas-Community#4]
Hello !

Christmas is coming soon...
Can you please make it possible to translate the interface ?
Once done, I promise I will provide the French translation of your resource file as a pull request.

Best regards and thank you !

Pierre

**Comment by Wingysam** [comment]
That's a great idea! I'll get started on it.

**Comment by smallketchup82** [comment]
hi yname

**Comment by DylanTheVillain101** [comment]
Hi ynamr

**Comment by Wingysam** [comment]
I've finished the localization system. If you'd like to add translations, copy [en-us.js](https://github.com/Wingysam/Christmas-Community/blob/master/languages/en-us.js) to fr-fr.js and update the contents. If there are too many strings, please let me know and I'll add a system to fall back to English if the language selected doesn't include a string.

If there are any issues, please let me know and I'll try to get it working.

Thank you! :)

**Comment by zethis** [comment]
Thanks man !

**Comment by drSchaps** [comment]
Hi Wingysam,
I noticed that the en-us.js file is missing translations for the Pledge/Unpledge buttons. Can you please fix it?
![image](https://user-images.githubusercontent.com/59886963/144879754-538f7725-20e0-42b1-9d3e-0e65cbc0506c.png)

**Comment by Wingysam** [comment]
Closed since it looks like I accidentally re-opened this after closing this. Please let me know if I've missed something.
