### ISSUE TITLE
Request: Ability to Change Page Headers from a Customization Menu

### ISSUE THREAD

**Issue by OneRadRedDad** [Wingysam/Christmas-Community#52]
It would be neat if one could change the Christmas Community text (in any of the spots in the attached screenshot of the login page) to something of their own choosing 
![image](https://user-images.githubusercontent.com/119024055/203904164-bdb6c02e-1878-43bd-8e94-7d09def75759.png)
If this feature was added, I wouldn't complain if " - Christmas Community" was appended to the custom titles or something.

**Comment by Wingysam** [comment]
You can currently do this with an environment variable but I'd like to add a config page at some point.

**Comment by Wingysam** [comment]
Config page issue: #64
