### ISSUE TITLE
Docker image for ARM64

### ISSUE THREAD

**Issue by fdw** [Wingysam/Christmas-Community#58]
I wanted to try it out on a RasPi, but unfortunately, there is no Docker image for arm64. Does it not work there? Do you think you could add one? 🙂

**Comment by Wingysam** [comment]
Definitely need an image for arm64. Maybe I can use qemu to build for it on x86?

**Comment by fdw** [comment]
I've seen other projects use [Docker buildx](https://github.com/docker/buildx#building-multi-platform-images) for cross-platform builds. Maybe that helps?

**Comment by Kimbaras** [comment]
Interested in this too!

**Comment by Wingysam** [comment]
I've been experimenting with building for arm64 from amd64 in another project today with success. Looking like I'll be able to do it here too!

**Comment by Wingysam** [comment]
Turns out it's incredibly easy to build arm64 images under WSL on x86 systems. This will definitely be happening at some point soon.

**Comment by sebPomme** [comment]
The image itself right now can directly be builded on raspi

**Comment by Wingysam** [comment]
Yeah it can be either built on arm hardware or you can use `docker build --platform=arm64`.

**Comment by Wingysam** [comment]
Yes, this command works for me with Docker Desktop:
```
docker build . -t christmas-community --platform=arm64
```

**Comment by fdw** [comment]
Awesome. Do you plan to publish it on Docker Hub or Github?

**Comment by Wingysam** [comment]
I've never pushed an image to GitHub before but I've been considering pushing to it over Docker Hub.

**Comment by Kimbaras** [comment]
I can confirm I was able to build and deploy the Docker image on a Raspberry Pi 4 (arm64).

Seems deploying / build on older Pis (3b+) is still a no go (tried to build with either arm32v6 and arm36v7 platforms but no results with either of those).
But judging by the title of the issue, I believe this is a different topic :D 

@Wingysam do you think you'll be able / willing to support also older Pis? If yes, I'll open a new issue dedicated to that, if not, I understand it.

Anyway, thanks for the support!

**Comment by Wingysam** [comment]
I'm not willing to test every release on older Pis to make sure I don't break it for them but I'll do what I can. What's the error trying to build on a 3b+?

**Comment by Wingysam** [comment]
The arm64 build is now on Docker Hub!
