### ISSUE TITLE
Request: Allow adding an alternative to a item

### ISSUE THREAD

**Issue by eastoncrafter** [Wingysam/Christmas-Community#59]
Something like the ability to add an alternative place to buy, or a link to a different item. So far I have just been putting it in the notes, but it would be nice to have some sort of integration

**Comment by eastoncrafter** [comment]
Or maybe an accessory to an item, something to go along with it

**Comment by Wingysam** [comment]
I think the benefit of this isn't worth the complexity tradeoff. Notes generally allow users to do this without having a dedicated field for it.
