### ISSUE TITLE
Request: Allow adding multiples of an item

### ISSUE THREAD

**Issue by OneRadRedDad** [Wingysam/Christmas-Community#60]
The default item count can be 1, but what if someone wants 2 of something, or 4, or more?

**Comment by Wingysam** [comment]
This can be achieved by either adding multiple of the item or writing it in the note. Is there a good reason to increase complexity by adding a dedicated field for this?

**Comment by OneRadRedDad** [comment]
I think a separate column would keep the UI clean and would prevent a user
from having to add too much to the Notes field

**Comment by Wingysam** [comment]
Should the count field also multiply the price?

**Comment by Wingysam** [comment]
That would have to be localized but that could work, thanks.

**Comment by oddstr13** [comment]
The only reason that I can think of for having a number field would be so that different people could pledge one each for example – this would complicate things quite a bit tho.

**Comment by Wingysam** [comment]
How should the UI for this look? Like say someone asks for 10 of an item and 9 different people have pledged one each, what should your screen look like?

**Comment by dathbe** [comment]
This is how Amazon handles it...basically comment bubbles:
![image](https://github.com/Wingysam/Christmas-Community/assets/14321825/0f3f7671-030f-4525-bc6b-9613de0d8266)
Users could always add their own comments to their own lists ("I'd like 5 of these"), but then gift givers would not be able to easily mark how many they've pledged.

I could come up with a fairly convoluted UI that would indicate how many you are asking for and how many have been pledged.  And then the pledge button would ask the giver how many they are pledging and allow the giver to un-pledge numbers.

But honestly, it's probably more straightforward to just add the item 5 times if you want 5 of them.

**Comment by Wingysam** [comment]
Yeah I think it's better to just duplicate the item.
