### ISSUE TITLE
can't delete items from wishlist

### ISSUE THREAD

**Issue by tzwaeaen** [Wingysam/Christmas-Community#68]
Hello,

I have the issue that I can't delete items from my wishlist. I receive the following error message: Error: Failed to find item

I can add, update or move items. I tried to call the delete url (/wishlist/user/delete/id) but it fails: Cannot GET /wishlist/user/delete/id

:-/

**Comment by Wingysam** [comment]
This is why automated testing / type checking is important. Will be fixed in a moment. Thanks for raising this!

**Comment by Wingysam** [comment]
Fixed in 1.30.3, published to Docker Hub.
