### ISSUE TITLE
How to set an initial admin password

### ISSUE THREAD

**Issue by indigo423** [Wingysam/Christmas-Community#70]
When I start the docker-compose stack, I get a login prompt but I haven't found a way to set up an admin user with a password. I've run the `docker-compose.yaml` stack here from the repository. When I get to `/` I get automatically redirected to the /login prompt. Any hints are appreciated.

**Comment by Wingysam** [comment]
If there are no users in the database when you visit `/`, you're given the form to create the admin user. If you have a blank instance and somehow have an empty admin user, consider just deleting the data directory and restarting.

**Comment by Wingysam** [comment]
@indigo423 any update on this?

**Comment by indigo423** [comment]
I've got it to work. I've just given it another spin today with the [latest image](https://hub.docker.com/layers/wingysam/christmas-community/latest/images/sha256-f56e80a688694b3612a6f39a5d56757bf18b2ce1148ffd04fdc80c53c1f6b0d7?context=explore) and it works as expected.
