### ISSUE TITLE
Strikethrough on pledged items in bulleted list

### ISSUE THREAD

**Issue by ndlanier** [Wingysam/Christmas-Community#73]
My mom and my sister got confused on what was already pledged and bought my wife the same gifts haha. From a usability standpoint, formatting pledged items from the main page with a strikethrough and possibly allowing it to be a numbered list instead would be good options to include in the env variables.

**Comment by Wingysam** [comment]
You're right! I don't think this needs to be a setting, this will be the only option. Flexibility is good but I don't think anyone would want the current behavior over the suggested behavior so it would create useless complexity.
