### ISSUE TITLE
Private wishlist

### ISSUE THREAD

**Issue by Outclass0026** [Wingysam/Christmas-Community#75]
Hi,
It would be nice to allow users to create "private" wishlists.
Usecase example: All the family use Christmas-Community for birthdays, christmas etc. So everyone already have an account and can see the list of eachh others. But I would like to create a hidden wishlist for my girlfriend with all the things I can purchase as a present for future occasion without her to be able to see it.
Hidden wishlist allow to keep the surprise for who will receive the gift but keep the utility of sharing lists with others members.

PS: Thanks for your great work!

**Comment by Wingysam** [comment]
You can't see items on your wishlist added by other people. Does that solve the issue?

**Comment by Outclass0026** [comment]
Yes it totally solve it, sorry if it was in the doc I've read it few days ago and maybe miss this part.
