### ISSUE TITLE
Feature Request: text on home page

### ISSUE THREAD

**Issue by mathisdt** [Wingysam/Christmas-Community#77]
First of all thank you for creating this useful application! I really appreciate it.

I would find one thing especially useful: A **configurable text which is displayed on the home page** (where all available lists are displayed). The text could be taken from an environment variable and be displayed between title and the first list. It could be directly copied to the HTML of the page, so the administrator could configure it using HTML tags.

The primary use of it would be (at least in my case) to point people without an account in the right direction to get one, maybe by publishing an email address or a link to an online form where an account can be requested. I as the administrator would then create the account and send the credentials back to them. This way everyone could make use of the wish lists. At the moment, I migrate from Amazon lists, and many people don't have an account yet, but I don't want to create accounts for them now which might get interpreted as "come on, give me a present".

I'm a Java backend developer and don't know Javascript more than the occasional "alert" method, but if there's a way I can help please say it. :smiley:

**Comment by mathisdt** [comment]
On second thought, the solution might also be a HTML snippet displayed below the login form. When anonymous users wants to reserve a present, they are redirected to the login, so if they don't have an account yet this might also be a sensible place for the notification on how to get an account.

**Comment by Wingysam** [comment]
I'll implement this today and push a new release. Thanks!

**Comment by Wingysam** [comment]
v1.32.0 implements `CUSTOM_HTML_LOGIN` and is building currently for Docker Hub.
