### ISSUE TITLE
Request: Ability to Add Custom CSS

### ISSUE THREAD

**Issue by Laeborg** [Wingysam/Christmas-Community#83]
Preferable an environment variable like `CUSTOM_CSS=/data/custom.css`

**Comment by Wingysam** [comment]
I can definitely add this! It should be in the next release.

**Comment by Laeborg** [comment]
I have opened pull request #85 with the functionality

**Comment by Laeborg** [comment]
As the Docker image is kinda old, I have temporary made a new version available here: https://hub.docker.com/r/laeborg/christmas-community
