### ISSUE TITLE
Receiving ERR_TOO_MANY_REDIRECTS when using NGINX

### ISSUE THREAD

**Issue by eastoncrafter** [Wingysam/Christmas-Community#99]
I am proxying christmas-community through an nginx reverse proxy, and I am receiving this error when attempting to access it remotely. This does not happen with any other service I run. Could it be a reverse proxy misconfiguration?

**Comment by Wingysam** [comment]
Likely related to #17.

**Comment by eastoncrafter** [comment]
Ah! Thanks, did a search for ERR_TOO_MANY_REDIRECTS and didn't find that.
Closing as duplicate of #17
